import re
from functools import lru_cache
import unicodedata

class NamesBuffer:
    class Movies:
        movie_names = {
        "Bill and Coo",
        "Shoe-Shine",
        "Song of the Open Road",
        "The House I Live In",
        "Clave",
        "Forbidden Games",
        "Gate of Hell",
        "Monsieur Vincent",
        "Rashomon",
        "Samurai",
        "Sis Hopkins",


        }
    class Countries:
        COUNTRY_ALIASES = {
            # alias -> kanon
            "uk": "United Kingdom", "u.k.": "United Kingdom",
            "usa": "United States", "u.s.a.": "United States",
            "ussr": "USSR", "u.s.s.r.": "USSR",
            "uae": "United Arab Emirates",
            "the netherlands": "Netherlands",
            "people's republic of china": "China",
            "the palestinian territories": "Palestinian Territories",
            "union of south africa": "South Africa",
            "the former yugoslav republic of macedonia": "North Macedonia",
            "federal republic of germany": "Germany",
            "german federal republic": "Germany",
            "german democratic republic": "Germany",
            "bosnia": "Bosnia and Herzegovina",
            "palestine": "Palestinian Territories",
            # literówka spotykana w źródłach:
            "colombia": "Colombia",
            "union of soviet socialist republics": "USSR",
        }

        COUNTRIES = {
            "usa","u.s.a.","uk","u.k.","soviet union","ussr","u.s.s.r.","poland","france","italy","spain",
            "germany","australia","canada","mexico","japan",'colombia',"china","india","brazil","argentina","sweden",
            "norway","denmark","finland","ireland","netherlands","belgium","czechoslovakia","czech republic",
            "slovakia","portugal","switzerland","austria","hungary","romania","bulgaria","greece","serbia",
            "croatia","slovenia","ukraine","belarus","lithuania","latvia","estonia","iceland","luxembourg",
            "monaco","andorra","liechtenstein","san marino","malta","south africa","nigeria","egypt",
            "morocco","algeria","ethiopia","kenya","ghana","senegal","new zealand","hong kong","taiwan",
            "south korea","north korea","turkey","iran","iraq","israel","lebanon","syria","jordan","uae",
            "qatar","kuwait","saudi arabia","vatican city","bhutan",
            "palestine","Kazakhstan",
            "Nepal",
            "Puerto Rico",
            "the palestinian territories",
            "USA", "UK", "U.S.A.", "U.K.", "USSR", "U.S.S.R.", "Soviet Union", "Czechoslovakia",
            "West Germany", "East Germany", "Yugoslavia", "Great Britain",
            # Europa
            "Poland", "France", "United Kingdom", "Italy", "Spain", "Portugal", "Germany", "Ireland", "Netherlands",
            "Belgium", "Norway",
            "Sweden", "Finland",
            "Denmark", "Iceland", "Switzerland", "Austria", "Hungary", "Czech Republic", "Slovakia", "Romania",
            "Bulgaria",
            "Greece",
            "Serbia", "Croatia", "Bosnia and Herzegovina", "Slovenia", "North Macedonia", "Albania", "Ukraine",
            "Belarus",
            "Lithuania",
            "Latvia", "Estonia", "Luxembourg", "Monaco", "Andorra", "Liechtenstein", "San Marino", "Vatican City",
            "Malta",
            # Ameryki
            "Mexico", 'Canada', "Brazil", "Argentina", "Chile", "Colombia", "Peru", "Uruguay", "Paraguay", "Bolivia",
            "Ecuador",
            "Venezuela", "Canada", "Cuba",
            # Azja
            "Japan", "China", "Hong Kong", "Taiwan", "South Korea", "North Korea", "India", "Iran", "Iraq", "Israel",
            "Jordan", "Lebanon",
            "Syria", "Saudi Arabia", "United Arab Emirates", "UAE", "Qatar", "Kuwait", "Turkey", "Georgia", "Armenia",
            "Azerbaijan",
            "Vietnam", "Thailand", "Malaysia", "Indonesia", "Singapore", "Philippines", "Pakistan", "Bangladesh",
            "Sri Lanka",
            # Afryka / Oceania
            "Egypt", "Morocco", "Tunisia", "Algeria", "South Africa", "Nigeria", "Ethiopia", "Kenya", "Ghana",
            "Senegal",
            "Australia", "New Zealand", 'Japan'
        }
    class Persons:
        PERSON_EXPANSIONS = {
            "sidney s. brod":"Sidney Sanford “Sid” Brod",
            "Alejandro G. Iñárritu's":"Alejandro González Iñárritu",
            "Alejandro G. Iñárritu":"Alejandro González Iñárritu",
            "Piero si":"Piero Tosi",
            "bunny dull metro-goldwyn-mayer":"Orville O. Dull, Metro-Goldwyn-Mayer",
            "w. howard greene":"William Howard Greene",
            "a. r. rahman": "Allah Rakha Rahman",
            "a. b. guthrie jr.": "Alfred Bertram Guthrie Jr.",
            "a. w. watkins": "Alfred Wilfred Watkins",
            "a. arnold gillespie": "Albert Arnold Gillespie",
            "a. earl hedrick": "Albert Earl Hedrick",
            "a. kitman ho": "Alexander Kitman Ho",
            "a. roland fields": "Ansel Roland Fields",
            "a. j. lohman": "August Lohman",
            "a.j. lohman": "August Lohman",
            "c. timothy o'meara": "Carroll Timothy O'Meara",
            "c. g. viola": "Cesare Giulio Viola",
            "c. c. stevens": "Charles Cyril Stevens",
            "c. c. coleman jr.": "Charles Clifford Coleman Jr.",
            "c. o. slyfield": "Charles O. Slyfield",
            "c. bakaleinikoff": "Constantin Bakaleinikoff",
            "jo allen": "Jo Allen",
            "kalman apple": "Kalman Apple",
            "tsai kuo jung": "Tsai Kuo Jung",
            "jj keith": "J. J. Keith",
            "pat mcclung": "Pat McClung",
            "tikki goldberg": "Tikki Goldberg",
            "herbie hancock": "Herbert Jeffrey Hancock",
            "b. tennyson sebastian ii": "B. Tennyson Sebastian II",
            "speed hopkins": "Speed Hopkins",
            "k.k. kapil": "K. K. Kapil",
            "j. gary mitchell": "J. Gary Mitchell",
            "jacquot ehrlich": "Jacquot Ehrlich",
            "lesley foster": "Lesley Foster",
            "tylwyth kymry": "Tylwyth Kymry (Meg Karlin)",
            "g. koshelev v. uvarov": "G. Koshelev, V. Uvarov",
            "fali bilimoria": "Fali Bilimoria",
            "deni vachlioti": "Deni Vachlioti",
            "valles": "Arlington Valles",
            "f. keogh gleason": "F. Keogh Gleason",
            "watson jones": "Watson Jones",
            "garson kanin": "Garson Kanin",
            "d'eaubonne": "D'Eaubonne",
            "doane harrison": "Doane Harrison",
            "hy heath": "Hy Heath",
            "d. m. marshman jr": "Donald McGill Marshman Jr.",
            "dr. miklos rozsa": "Miklos Rozsa",
            "devereux jennings": "Devereux Jennings",
            "farciot edouart": "Farciot Edouart",
            "eleazar lipsky": "Eleazar Lipsky",
            "moss hart": "Moss Hart",
            "colonel william n. selig": "William N. Selig",
            "georgie stoll": "Georgie Stoll",
            "e. y. harburg": "Yip Harburg",
            "ferde grofe": "Ferde Grofé",
            "haldane douglas": "Haldane Douglas",
            "lt. john koenig": "John Koenig",
            "r. o. binger": "R. O. Binger",
            "dashiell hammett": "Samuel Dashiell Hammett",
            "casey roberts": "Casey Roberts",
            "ring lardner jr.": "Ringgold Wilmer Lardner Jr.",
            "w. r. burnett": "William Riley Burnett",
            "jo swerling": "Jo Swerling",
            "dr. hugo riesenfeld": "Hugo Riesenfeld",
            "w. s. van dyke": "Woodbridge Strong Van Dyke",
            "kubec glasmon": "Kubec Glasmon",
            "nugent slaughter": "Nugent Slaughter",
            # sceniczne — domyślnie bez expansion
            "the weeknd": "Abel Makkonen Tesfaye",
            "the edge": "David Howell Evans",
            "dixson": "Darius Scott",
            "topol": "Chaim Topol",
            "mako": "Makoto Iwamatsu",
            # inicjały, skróty
            "r. christopher white": "Christopher White",
            "k.d. dávila": "Kristen Dávila",
            "k. d. dávila": "Kristen Dávila",
            "d.m. hemphill": "David M. Hemphill",
            "d. m. hemphill": "David M. Hemphill",
            "j. christian jensen": "J. Christian Jensen",
            "j. miles dale": "J. Miles Dale",
            "j.c. chandor": "J. C. Chandor",
            "j.c. carrière": "J. C. Carrière",
            # sceniczne, opcjonalnie do expansion
            "bloodpop": "Michael Tucker",
            "h.e.r": "Gabriella Wilson",
            "lady gaga": "Stefani Germanotta",
            "tems": "Temilade Openiyi",
            "mitski": "Mitski Miyawaki",

        }
        PERSON_GENDER_OVR = {
            "a. b. guthrie jr": "male",
            "alfred bertram guthrie jr.": "male",
            "a. d. flowers": "male",
            "arthur d. flowers": "male",
            "a. kitman ho": "male",
            "a. roland fields": "male",
            "ansel roland fields": "male",
            "roland a. fields": "male",
            "a.j. lohman": "male",
            "a. j. lohman": "male",
            "august lohman": "male",
            "a.r. rahman": "male",
            "a. r. rahman": "male",
            "allah rakha rahman": "male",
            "luc-ewen martin-fenouillet": "male",
            "pat pending": "male",
            "r. t. layton": "male",
            "the weeknd": "male",
            "the edge": "male",
            "dixson": "male",
            "topol": "male",
            "mako": "male",
            "jo allen": "female",
            "kalman apple": "male",
            "tsai kuo jung": "male",
            "jj keith": "male",
            "pat mcclung": "male",
            "tikki goldberg": "female",
            "herbie hancock": "male",
            "b. tennyson sebastian ii": "male",
            "speed hopkins": "male",
            "k.k. kapil": "male",
            "j. gary mitchell": "male",
            "jacquot ehrlich": "male",
            "lesley foster": "female",
            "tylwyth kymry": "female",
            "g. koshelev v. uvarov": "male",
            "fali bilimoria": "male",
            "deni vachlioti": "female",
            "valles": "male",
            "f. keogh gleason": "male",
            "watson jones": "male",
            "garson kanin": "male",
            "d'eaubonne": "male",
            "doane harrison": "male",
            "hy heath": "male",
            "d. m. marshman jr": "male",
            "dr. miklos rozsa": "male",
            "devereux jennings": "male",
            "farciot edouart": "male",
            "eleazar lipsky": "male",
            "moss hart": "male",
            "colonel william n. selig": "male",
            "georgie stoll": "male",
            "e. y. harburg": "male",
            "ferde grofe": "male",
            "haldane douglas": "male",
            "lt. john koenig": "male",
            "r. o. binger": "male",
            "dashiell hammett": "male",
            "casey roberts": "male",
            "ring lardner jr.": "male",
            "w. r. burnett": "male",
            "jo swerling": "male",
            "dr. hugo riesenfeld": "male",
            "w. s. van dyke": "male",
            "kubec glasmon": "male",
            "nugent slaughter": "male",
            # AZJA / TRUDNE / FESTIWALE
            "hayao miyazaki": "male",
            "yorgos lanthimos": "male",
            "yorgos mavropsaridis": "male",
            "yorgos lamprinos": "male",
            "mstyslav chernov": "male",
            "kazu hiro": "male",
            "bong joon ho": "male",
            "yang jinmo": "male",
            "yi seung-jun": "male",
            "cho won woo": "male",
            "han jin won": "male",
            "siqi song": "female",
            "meryam joobeur": "female",
            "waad al-kateab": "female",
            "kaouther ben hania": "female",
            "kartiki gonsalves": "female",
            "guneet monga": "female",
            "shaunak sen": "male",
            "raney aronson-rath": "female",
            "s. leo chiang": "male",
            "tal kantor": "female",
            "yegane moghaddam": "female",
            "misan harriman": "male",
            "celine song": "female",
            "joão gonzalez": "male",
            "ehren kruger": "male",
            "euzhan palcy": "female",
            "yvett merino": "female",
            'ahmir "questlove" thompson': "male",
            'ahmir questlove thompson': "male",
            "gulistan mirzaei": "male",
            "dernst emile ii": "male",
            "fat max gsus": "male",
            "josey mcnamara": "male",
            "gísli darri halldórsson": "male",
            "jarin blaschke": "male",
            "joshuah brian campbell": "male",
            "kwak sin ae": "female",
            "krysty wilson-cairns": "female",
            "lukasz zal": "male",
            "raMell ross".lower(): "male",
            "su kim": "female",
            "bing liu": "male",
            "j.d. schwalm": "male",
            "yance ford": "male",
            "ru kuwahata": "female",
            "derin seale": "male",
            "hébert peck": "male",
            "kahane cooperman": "female",
            "giacun caduff": "male",
            "aske bang": "male",
            "juanjo giménez": "male",
            "tarell alvin mccraney": "male",
            "den tolmor": "male",
            "nomi talisman": "female",
            "lesley vanderwalt": "female",
            "anohni": "female",
            "blye pagon faust": "female",
            "pato escala": "male",
            "s. leigh savidge": "male",
            "j. christian jensen": "male",
            "hu wei": "male",
            "talkhon hamzavi": "female",
            "e. max frye": "male",
            "minkyu lee": "male",
            "pes": "male",
            "j. roy helland": "male",
            "carlinhos brown": "male",
            "siedah garrett": "female",
            "oorlagh george": "female",
            "celine rattray": "female",
            "geefwee boedoe": "male",
            "ash brannon": "male",
            "maciek szczerbowski": "male",
            "diablo cody": "female",
            "yee chung man": "male",
            "byambasuren davaa": "female",
            "sejong park": "male",
            "baker bloodworth": "male",
            "ashvin kumar": "male",
            "dien van straalen": "female",
            "dominique monfery": "male",
            "hervé de luze": "male",
            "benoit charest".replace("oî", "oît"): "male",
            # grecja / francja / bałkany
            "stephane ceretti": "male",
            "stephane grabli": "male",
            "efthimis filippou": "male",
            "cécile (ceci) dempsey": "female",
            "ceci dempsey": "female",

            # muza / songwriterzy / sceniczne
            "bloodpop": "male",
            "lady gaga": "female",
            "tems": "female",
            "mitski": "female",
            "baz luhrmann": "male",
            "finneas o'connell": "male",
            "beyoncé knowles-carter": "female",
            "savan kotecha": "male",
            "atticus ross": "male",
            "t bone burnett": "male",
            "sufjan stevens": "male",
            "sting": "male",
            "pharrell williams": "male",
            "chandrabose": "male",
            "m.m. keeravaani": "male",

            # dokument / animacja
            "domee shi": "female",
            "caitrin rogers": "female",
            "jehane noujaim": "female",
            "marjane satrapi": "female",
            "sharmeen obaid-chinoy": "female",
            "rintu thomas": "female",
            "sushmit ghosh": "male",
            "gini reticker": "female",

            # hollywood / producenci / hair-makeup
            "jent yates": "female",  # jeśli masz "janty yates" to niżej ↓
            "janty yates": "female",
            "lesley paterson": "female",
            "marese langan": "female",
            "mayes c. rubeo": "female",
            "ve neill": "female",
            "stephenie mcmillan": "female",
            "ceán chaffin": "female",
            "jinko gotoh": "female",
            "joi mcmillon": "female",
            "mollye asher": "female",
            "jenno topping": "female",
            "peilin chou": "female",
            "gennie rim": "female",
            "marie-ange luciani": "female",
            "lin-manuel miranda": "male",
            "jean-louis livi": "male",
            "jayne-ann tenggren": "female",
            "jean-françois le corre": "male",
            "spike lee": "male",
            "marie-hélène panisset": "female",
            "ai-ling lee": "female",
            "lalo schifrin": "male",
            "benj pasek": "male",
            "kumail nanjiani": "male",
            "j. ralph": "male",
            "jackie chan": "male",
            "oprah winfrey": "female",
            "spike jonze": "male",
            "k.k. barrett": "male",
            "ang lee": "male",
            "benh zeitlin": "male",
            "mychael danna": "male",
            "bombay jayashri": "female",
            "claude-michel schönberg": "male",
            "erik-jan de boer": "male",
            "d.a. pennebaker": "male",
            "jean-loup felicioli": "male",
            "lisy christl": "female",
            "gian-piero ringel": "male",
            "anne-sophie bion": "female",
            "j.c. chandor": "male",
            "carolynne cunningham": "female",
            "tivi magnusson": "male",
            "thavisouk phrasavath": "male",
            "emud mokhberi": "male",
            "hawk ostby": "male",
            "henry-alex rubin": "male",
            "hughes winborne": "male",
            "zhao xiaoding": "male",
            "benoît charest": "male",
            "stefen fangmeier": "male",
            "eminem": "male",
            "marie-laure valla": "female",
            "jean-xavier de lestrade": "male",
            "edet belzberg": "female",
            "b.z. goldberg": "male",
            "dody dorn": "female",
            "slawomir fabicki": "male",
            "merideth boswell": "female",
            "crispian sallis": "male",
            "françoise benoît-fresco": "female",
            "leelai demoz": "male",
            "saar klein": "male",
            "björk": "female",
            "hsu li kong": "male",
            "wang hui ling": "female",
            "m. night shyamalan": "male",
            "lilibet foster": "female",
            "marc-andreas bochert": "male",
            "shui-bo wang": "male",
            "gwil owen": "male",
            "pud cusack": "female",
            "atom egoyan": "male",
            "rabbi marvin hier": "male",
            "kieth merrill": "male",
            "pearse moore": "male",
            "milos forman": "male",
            "jo menell": "male",
            "bayley silleck": "male",
            "pip karmel": "female",
            "jud j. friedman": "male",
            "jud friedman": "male",
            "lu yue": "male",
            "alexij kharitidi": "male",
            "dorree cooper": "female",
            "moidele bickel": "female",
            "gu changwei": "male",
            "renner wunderlich": "female",
            "clif magness": "male",
            "immy humes": "female",
            "f. hudson miller": "male",
            "pat conroy": "male",
            "barbet schroeder": "male",
            "shel silverstein": "male",
            "whit stillman": "male",
            "bari dreiband-burman": "female",
            "abbee goldstein": "female",
            "thaine morris": "male",
            "dr. frank daniel": "male",
            "brasse brännström": "male",
            "amram nowak": "male",
            "bran ferren": "male",
            "hesper anderson": "female",
            "raynold gideon": "male",
            "j. michael riva": "male",
            "asakazu nakai": "male",
            "donfeld": "male",
            "japhet asher": "male",
            "zoltan elek": "male",
            "andrae crouch": "male",
            "caiphus semenya": "male",
            "horton foote": "male",
            "ishu patel": "male",
            "p.h. vazak": "male",
            "babaloo mandel": "male",
            "w. stewart campbell": "male",
            "marik vos": "female",
            "burny mattinson": "male",
            "m. j. frankovich": "male",
            "bhanu athaiya": "female",
            "frankie sullivan iii": "male",
            "costa-gavras": "male",
            "assheton gorton": "male",
            "tambi larsen": "male",
            "tete vasconcellos": "male",
            "pen densham": "male",
            "lesley gore": "female",
            "w. d. richter": "male",
            "h.r. giger": "male",
            "eustace lycett": "male",
            "t.s. cook": "male",
            "curly thirlwell": "male",
            "jean-louis ducarme": "male",
            "charlton heston": "male",
            "sparky greene": "male",
            "jean-charles tacchella": "male",
            "l. b. abbott": "male",
            "pandro s. berman": "male",
            "ulla-britt soderlund": "female",
            "f. r. crawley": "male",
            "lynzee klingman": "female",
            "dr. jules c. stein": "male",
            "e. preston ames": "male",
            "francois truffaut": "male",
            "danford greene": "male",
            "danford b. greene": "male",
            "euel box": "male",
            "jean-louis richard": "male",
            "moss mabry": "male",
            "groucho marx": "male",
            "walon green": "male",
            "han van gelder": "male",
            "folmar blangsted": "male",
            "pierre-louis thevenet": "male",
            "urie mccleary": "male",
            "taizoh kawashima": "male",
            "osami furuya": "male",
            "sinsaku himeda": "male",
            "dr. harald reinl": "male",
            "ely landau": "male",
            "riz ortolani": "male",
            "ring lardner jr": "male",
            "françoise bonnot": "female",
            "luchino visconti": "male",
            "jule styne": "male",
            "j. mcmillan johnson": "male",
            "elven webb": "male",
            "burnett guffey": "male",
            "devol": "male",
            "jean-charles meunier": "male",
            "j. terry williams": "male",
            "friz freleng": "male",
            "waldon o. watson": "male",
            "i. a. l. diamond": "male",
            "y. frank freeman": "male",
            "marshal backlar": "male",
            "tregoweth brown": "male",
            "scarpelli": "male",
            "suso cecchi d'amico": "female",
            "vassilis fotopoulos": "male",
            "jacques-yves cousteau": "male",
            "oxley hughan": "male",
            "cotton warburton": "male",
            "s. h. barnett": "male",
            "hilyard brown": "male",
            "addison hehr": "male",
            "algernon g. walker": "male",
            "dusan vukotic": "male",
            "ub iwerks": "male",
            "orry-kelly": "male",
            "bronislau kaper": "male",
            "j.c. carrière": "male",
            "veniero colasanti": "male",
            "j. lee thompson": "male",
            "miklos rozsa": "male",
            "dr. john d. jennings": "male",
            "frantisek vystrecil": "male",
            "nedrick young": "male",
            "t. e. b. clarke": "male",
            "keogh gleason": "male",
            "thorold dickinson": "male",
            "g. rozhdestvensky": "male",
            "melville shavelson": "male",
            "dr. wesley c. miller": "male",
            "r. wright campbell": "male",
            "b.b. kahane": "male",
            "o. dalsgaard-olsen": "male",
            "s.j. perelman": "male",
            "tennessee williams": "male",
            "jo mielziner": "male",
            "tadaoto kainoscho": "male",
            "hy zaret": "male",
            "beirne lay jr": "male",
            "sanzo wada": "male",
            "morrie roizman": "male",
            "françois boyer": "male",
            "budd schulberg": "male",
            "kemp r. niver": "male",
            "castleton knight": "male",
            "h. motsumoto": "male",
            "winton c. hoch": "male",
            "winton hoch": "male",
            "f. a. young": "male",
            "madame karinska": "female",
            "gile steele": "male",
            "hall bartlett": "male",
            "gian-carlo menotti": "male",
            "merian c. cooper": "male",
            "hoagy carmichael": "male",
            "col. nathan levinson": "male",
            "colonel nathan levinson": "male",
            "budd boetticher": "male",
            "lesser samuels": "male",
            "ramey idriss": "male",
            "borden chase": "male",
            "millen brand": "male",
            "peverell marley": "male",
            "clemence dane": "female",
            "f. fellini": "male",
            "nunnally johnson": "male",
            "laszlo gorog": "male",
            "alvah bessie": "male",
            "mark-lee kirk": "male",
            "abem finkel": "male",
            "monckton hoffe": "male",
            "seton i. miller": "male",
            "rey scott": "male",
            "osmond borradaile": "male",
            "lud gluskin": "male",
            "r. c. sherriff": "male",
            "j. arthur ball": "male",
            "hunt stromberg": "male",
            "c. c. coleman jr": "male",
            "busby berkeley": "male",
            "w. franke harling": "male",
            "niven busch": "male",
            "casey robinson": "male",
            "achmed abdullah": "male",
            "carey wilson": "male",
            "grantland rice": "male",
            "m. k. jerome": "male",
            "e. h. hansen": "male",
            "h. j. salter": "male",
            # faceci, których heurystyka nie pozna
            "kemp powers": "male",
            "tarn willers": "male",
            "jerskin fendrix": "male",
            "michellee couttolenc": "female",
            "phedon papamichael": "male",
            "d. m. hemphill": "male",
            "d.m. hemphill": "male",
            "ren klyce": "male",
            "carthew neal": "male",
            "tevo díaz": "male",
            "aneil karia": "male",
            "mikey please": "male",
            "r. christopher white": "male",
            "j. miles dale": "male",
            "riz ahmed": "male",
            "k. k. barrett": "male",
            "baldwin li": "male",
            "kief davidson": "male",
            "jedd wider": "male",
            "tj martin": "male",
            "danfung dennis": "male",
            "brunson green": "male",
            "hallvar witzø": "male",
            "fisher stevens": "male",
            "carey villegas": "male",
            "ged wright": "male",
            "addison teague": "male",
            "moh en leo": "male",  # jeśli masz "Mohen Leo"
            "mohen leo": "male",
            "doc kane": "male",
            "bub asman": "male",
            "banksy": "male",
            "dice tsutsumi": "male",
            "hammond peek": "male",
            "petur hliddal": "male",
            "tomek baginski": "male",
            "slawomir idziak": "male",
            "bartek konopka": "male",
            "thavisouk phrassavath": "male",
            "thavisouk phr asavath": "male",
            "thavisouk phr asvath": "male",
        }
        GROUP_OVERRIDES = {
            "the beatles": "The Beatles",
            "leopold stokowski and his associates": "Leopold Stokowski and his associates",
        }

    class Organizations:
        ORG_OVERRIDES = {
            # studia / imprinty i działy dźwięku (częste warianty z listy)
            "st. francis-xavier university, antigonish, nova scotia": "St. Francis Xavier University",
            "the National Endowment for the Arts": "The National Endowment for the Arts",
            "United States Department of State Office of Information and Educational Exchange":"United States Department of Educational Exchange",
            "warner bros": "Warner Bros.",
            "Amkino": "Amkino",
            "Ciné-Documents": "Ciné-Documents",
            "French Cinema General Cooperative": "French Cinema General Cooperative",
            "Gaumont British": "Gaumont British",
            "Harman-Ising": "Harman-Ising",
            "J. Arthur Rank-Archers": "J. Arthur Rank-Archers",
            "J. Arthur Rank-Cineguild": "J. Arthur Rank-Cineguild",
            "Mercury": "Mercury",
            "Ortus": "Ortus",
            "Realization D'Art Cinematographique": "Réalisation d'Art Cinématographique",
            "Screen Gems": "Screen Gems",
            "Statens Filmcentral": "Statens Filmcentral",
            "Two Cities": "Two Cities",
            "United Artists": "United Artists",
            "Visual Information": "Visual Information",
            "warner bros. studio": "Warner Bros.",
            "warner bros.-first national": "Warner Bros.",
            "warner bros.-seven arts studio sound department": "Warner Bros.-Seven Arts",
            "20th century": "20th Century Fox",
            "20th century-fox": "20th Century Fox",
            "20th century-fox studio": "20th Century Fox",
            "20th century-fox film corporation": "20th Century Fox",
            "20th century-fox studio sound department": "20th Century Fox",
            "paramount": "Paramount Pictures",
            "paramount studio": "Paramount Pictures",
            "paramount famous lasky": "Paramount Famous Lasky",
            "paramount publix": "Paramount Publix",
            "paramount publix studio sound department": "Paramount Publix",
            "columbia": "Columbia Pictures",
            "columbia studio sound department": "Columbia Pictures",
            "universal": "Universal Pictures",
            "universal city studio sound department": "Universal Pictures",
            "metro-goldwyn-mayer": "Metro-Goldwyn-Mayer",
            "metro-goldwyn-mayer studio": "Metro-Goldwyn-Mayer",
            "samuel goldwyn productions": "Samuel Goldwyn Productions",
            "samuel goldwyn": "Samuel Goldwyn Productions",
            "samuel goldwyn jr.": "Samuel Goldwyn Productions",
            "samuel goldwyn studio sound department": "Samuel Goldwyn Productions",
            "rko radio": "RKO Radio Pictures",
            "fox":'Fox Film Corporation',
            "rko radio studio sound department": "RKO Radio Pictures",
            "london film production": "London Film",
            "london film sound department": "London Film",
            "pinewood studios sound department": "Pinewood Studios",
            "shepperton studio sound department": "Shepperton Studios",
            "national film board of canada": "National Film Board of Canada",
            "the national film board of canada": "National Film Board of Canada",
            "the danish government film office": "Danish Government Film Office",
            "the government film committee of denmark": "Government Film Committee of Denmark",
            "the netherlands information bureau": "Netherlands Information Bureau",
            "polish information centre": "Polish Information Centre",
            "united productions of america": "United Productions of America",
            "the society of motion picture": "The Society of Motion Picture",
            "the society of motion picture and television engineers": "SMPTE",
            "rca sound": "RCA",
            "sound service": "Sound Service",
            "westrex sound services": "Westrex Sound Services",
            "bausch & lomb optical company": "Bausch & Lomb Optical Company",
            "lomb optical company": "Lomb Optical Company",
            "bell and howell company": "Bell & Howell",
            "dublin gate theatre productions": "Dublin Gate Theatre Productions",
            "vision associates productions": "Vision Associates Productions",
            "new zealand screen board": "New Zealand Screen Board",
            "comite organizador de los juegos de la xix olimpiada": "Mexico City 1968 Organizing Committee",
            "comitato organizzatore del giochi della xvii olimpiade": "Rome 1960 Organizing Committee",
            "dell istituto nazionale luce": "Istituto Luce Cinecittà",
            "cosmopolitan": "Cosmopolitan Productions",
            "educational": "Educational Pictures",
            "first national": "First National Pictures",
            "feature productions": "Feature Productions",
            "selznick international pictures": "Selznick International Pictures",
            "argosy-wanger": "Argosy-Wanger",
            "skibo productions": "Skibo Productions",
            "universal pictures": "Universal Pictures",
            "republic studio sound department": "Republic Pictures",
            "associates inc": "Associates Inc.",
            "film documents inc": "Film Documents Inc.",
            "eastman kodak company": "Eastman Kodak Company",
            "united states information agency": "USIA",
            "united states air force": "United States Air Force",
            "danish government film office": "Danish Government Film Office",
            "government film committee of denmark": "Government Film Committee of Denmark",
            "rome 1960 organizing committee": "Rome 1960 Organizing Committee",
            "mexico city 1968 organizing committee": "Mexico City 1968 Organizing Committee",
            "The March of Time":"The March of Time",
            "Artkino":"Artkino",
            "United States Merchant Marine":"United States Merchant Marine",
            "The Governments of Great Britain":"The Government of Great Britain",
            "the United States of America":"The Government of United States of America",
            "Australian News":"Australia News",
            "the Technicolor Company":"The Technicolor Company",
        }
        ORG_HINTS = (
            r"studio|studios|records|sound\s+department|department|division|unit|office|academy|association|ministry|committee|board|council|"
            r"pictures?|productions?|entertainment|film(?:s)?|television|broadcast|radio|network|channel|"
            r"university|college|school|institute|foundation|fund|archive|library|museum|"
            r"company|co\.?|corp\.?|corporation|inc\.?|ltd\.?|llc|llp|plc|ag|gmbh|s\.a\.|s\.r\.l\.|b\.v\.|s\.p\.a\.|pte|pty|sa|sas|as|ab|"
            r"army|navy|air\s*force|marine\s*corps|coast\s*guard|government|bureau|service|agency"
        )

    @classmethod
    @lru_cache(maxsize=1)
    def registry(cls):
        cf = str.casefold
        #  countries
        aliases = {cf(k): v for k, v in cls.Countries.COUNTRY_ALIASES.items()}
        countries = {cf(c) for c in cls.Countries.COUNTRIES}
        countries |= {cf(v) for v in aliases.values()}
        movies = {cf(m) for m in cls.Movies.movie_names}
        #  organizations
        org_overrides = {cf(k): v for k,v in cls.Organizations.ORG_OVERRIDES.items()}
        org_re = re.compile(rf"\b(?:{cls.Organizations.ORG_HINTS})\b",re.I)
        #  persons
        person_exp = {cf(k): v for k, v in cls.Persons.PERSON_EXPANSIONS.items()}
        gender_ovr = {cf(k): v for k, v in cls.Persons.PERSON_GENDER_OVR.items()}
        groups = {cf(k): v for k, v in cls.Persons.GROUP_OVERRIDES.items()}
        return{
            'countries': countries,
            'country_aliases':aliases,
            'org_re':org_re,
            'org_overrides':org_overrides,
            'person_exp':person_exp,
            'gender_ovr':gender_ovr,
            'groups':groups,
            'movies':movies,
        }

    @classmethod
    def _norm_key(cls, s):
        return unicodedata.normalize("NFKC", (s or '').strip()).casefold()

    @classmethod
    def normalize_entity(cls, s: str) -> str:
        if not s:
            return ""
        reg = cls.registry()
        key = cls._norm_key(s)

        if key in reg["org_overrides"]:
            return reg["org_overrides"][key]
        if key in reg["person_exp"]:
            return reg['person_exp'][key]
        if reg["org_re"].search(s):
            return s.strip()

        return s.strip()

    @classmethod
    def is_country(cls,entity):
        reg = cls.registry()
        key = cls._norm_key(entity)
        if not key:
            return False
        alias_target = reg['country_aliases'].get(key,key)
        key = str.casefold(alias_target)
        return key if key in reg['countries'] else False

